# Travis-CI yaml setting for CMSiMDE site
language: python
os: linux
sudo: required
python: "3.7"
dist: xenial
install:
  - pip install -r requirements.txt -U
script:
  - pelican markdown -o blog -s publishconf.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  on:
    branch: master
