# Travis-CI yaml setting for CMSiMDE site
language: python
os: linux
sudo: required
python: "3.7"
dist: xenial
install:
  - pip install -r requirements.txt -U
script:
  - pelican markdown -o blog -s publishconf.py
after_success:
  - cd blog
  - git add ./
  - git -c user.name="Travis CI for Scrum-1" -c user.email="<scrum1>@mde.tw" commit -m 'Travis update Pelican blog'
  - cd ..
  - @git push -fq https://${GH_TOKEN}@github.com/$(TRAVIS_REPO_SLUG).git master > /dev/null
