# Travis-CI for CMSiMDE site
language: python
os: linux
sudo: required
python: "3.7"
dist: xenial
before_install:
  - pip install -r requirements.txt -U
install:
  - pelican markdown -o blog -s publishconf.py
after_success:
  - cd blog
  - git add ./
  - git -c user.name="Travis CI for Scrum-1" -c user.email="<scrum1>@mde.tw" commit -m 'Travis update Pelican blog'
  - git push https://${GH_TOKEN}@github.com/scrum-1/cp2019.git master
